### ISSUE TITLE
分隔符过滤匹配带有空格数据无法采集到数据

### ISSUE THREAD

**Issue by Eli-ZhangLu** [TencentBlueKing/bk-log#932]
**数据接入配置日志内容过滤规则，采用分隔符过滤，匹配字段前后带有空格数据无法采集到日志数据**:

- 采集接入配置：采用","分割，匹配第二列包含“ after callback”（字符串前面带有空格），编辑查看详情已将空格自动删除；
![image](https://user-images.githubusercontent.com/30516472/165092371-1d1d8914-d850-47ef-b177-e29207815dbd.png)
![image](https://user-images.githubusercontent.com/30516472/165093976-638e3f21-ba00-4dc4-aba4-3d7ea3c269f5.png)

- 问题原因
1. django 序列化器默认将空格删除（默认trim_whitespace=True）；
![image](https://user-images.githubusercontent.com/30516472/165092866-3f691757-cb0b-4ba0-9071-96502aba3a93.png)

2. 下发的采集配置文件已将空格取消，但采集器匹配内容的时候分割日志后是带空格去匹配关键字的，导致匹配不到内容；
![image](https://user-images.githubusercontent.com/30516472/165094057-31a86d8a-8956-4fcf-a0f1-b123021fd58a.png)
![image](https://user-images.githubusercontent.com/30516472/165094137-e170d3f5-7db2-477c-b821-426b645b6292.png)

- 解决方案

1. 方案一：修改序列器，增加trim_whitespace=False;
2. 方案二：修改采集器匹配逻辑，分割完去除前后空格去匹配关键字（个人建议采用该方案，因为空格内容对用户无意义）；
![image](https://user-images.githubusercontent.com/30516472/165094191-a81f258b-894c-4d5a-8144-ea142955ffaa.png)

**Comment by liuwenping** [comment]
https://github.com/TencentBlueKing/bkunifylogbeat/pull/35
